services:
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: simdesk
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    volumes:
      - simdesk-db:/var/lib/postgresql/data

volumes:
  simdesk-db: